import { Dimensions, StyleSheet } from "react-native";
const { width } = Dimensions.get('window');

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f8f9fa',
    },
    stickyHeader: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        height: 70,
        backgroundColor: '#fff',
        zIndex: 1000,
        paddingTop: 15,
        paddingHorizontal: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowRadius: 4,
        shadowOffset: { width: 0, height: 2 },
        elevation: 4,
    },
    stickyContent: {
        flexDirection: 'row',
        alignItems: 'center',
        height: 44,
    },
    stickyLogoContainer: {
        marginRight: 12,
    },
    stickyAppIcon: {
        width: 32,
        height: 32,
        borderRadius: 8,
        backgroundColor: '#6200ea15',
        justifyContent: 'center',
        alignItems: 'center',
    },
    stickyIconText: {
        fontSize: 16,
    },
    stickySearchContainer: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f8f9fa',
        borderRadius: 12,
        paddingHorizontal: 12,
        height: 40,
        marginRight: 12,
    },
    stickySearchPlaceholder: {
        flex: 1,
        fontSize: 14,
        color: '#999',
        marginLeft: 8,
    },
    stickyNotificationButton: {
        position: 'relative',
        padding: 6,
    },
    header: {
        backgroundColor: '#fff',
        paddingTop: 25,
        paddingHorizontal: 20,
        paddingBottom: 20,
        borderBottomLeftRadius: 24,
        borderBottomRightRadius: 24,
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 4 },
        elevation: 5,
    },
    headerTop: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    logoContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    appIcon: {
        width: 40,
        height: 40,
        borderRadius: 12,
        backgroundColor: '#6200ea15',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    iconText: {
        fontSize: 20,
    },
    appName: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#1a1a1a',
    },
    notificationButton: {
        position: 'relative',
        padding: 8,
    },
    notificationBadge: {
        position: 'absolute',
        top: 8,
        right: 8,
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: '#FF6B6B',
    },
    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f8f9fa',
        borderRadius: 16,
        paddingHorizontal: 16,
        height: 48,
    },
    searchIcon: {
        marginRight: 12,
    },
    searchPlaceholder: {
        flex: 1,
        fontSize: 16,
        color: '#999',
    },
    filterButton: {
        padding: 4,
    },
    section: {
        marginTop: 24,
        paddingHorizontal: 20,
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 1,
    },
    sectionTitle: {
        fontSize: 22,
        fontWeight: 'bold',
        color: '#1a1a1a',
        marginBottom: 7,
    },
    seeAllText: {
        fontSize: 16,
        color: '#6200ea',
        fontWeight: '600',
    },
    // Featured Section
    featuredContainer: {
        flexDirection: 'row',
        paddingRight: 20,
    },
    featuredCard: {
        width: width * 0.7,
        height: 200,
        borderRadius: 20,
        marginRight: 16,
        overflow: 'hidden',
        position: 'relative',
    },
    featuredImage: {
        width: '100%',
        height: '100%',
        resizeMode: 'cover',
    },
    featuredOverlay: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        height: '60%',
        backgroundColor: 'rgba(0,0,0,0.6)',
        padding: 16,
        justifyContent: 'space-between',
    },
    featuredBadge: {
        backgroundColor: '#FF6B6B',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 12,
        alignSelf: 'flex-start',
    },
    featuredBadgeText: {
        color: '#fff',
        fontSize: 10,
        fontWeight: 'bold',
    },
    featuredInfo: {
        // marginTop: 'auto',
    },
    featuredTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#fff',
        marginBottom: 4,
    },
    featuredAuthor: {
        fontSize: 14,
        color: '#ccc',
        marginBottom: 8,
    },
    featuredFooter: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    featuredRating: {
        fontSize: 14,
        color: '#fff',
        marginLeft: 4,
        fontWeight: '600',
    },
    featuredPrice: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#fff',
    },
    // Categories
    categoriesScroll: {
        padding: 4,
        marginBottom: 20
    },
    categoryItem: {
        alignItems: 'center',
        padding: 10,
        marginRight: 10,
        borderRadius: 7,
        backgroundColor: '#fff',
        minWidth: 80,
        shadowColor: '#000',
        shadowOpacity: 0.05,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 2 },
        elevation: 2,
    },
    categoryItemActive: {
        backgroundColor: '#6200ea',
        transform: [{ scale: 1.05 }],
    },
    categoryName: {
        fontSize: 14,
        fontWeight: '600',
        color: '#666',
    },
    categoryNameActive: {
        color: '#fff',
    },
    horizontalList: {
        flexDirection: 'row',
    },
    horizontalBookCard: {
        marginRight: 16,
    },
    booksGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
    },
    gridBookCard: {
        width: '48%',
        marginBottom: 16,
    },
    bookCard: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 12,
        shadowColor: '#000',
        shadowOpacity: 0.08,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: 4 },
        elevation: 3,
        width: 160,
    },
    bookImageContainer: {
        position: 'relative',
        marginBottom: 12,
    },
    bookImage: {
        width: '100%',
        height: 180,
        borderRadius: 12,
        backgroundColor: '#f0f0f0',
    },
    newBadge: {
        position: 'absolute',
        top: 8,
        left: 8,
        backgroundColor: '#4ECDC4',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 8,
    },
    popularBadge: {
        position: 'absolute',
        top: 8,
        left: 8,
        backgroundColor: '#FF6B6B',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 8,
    },
    badgeText: {
        color: '#fff',
        fontSize: 10,
        fontWeight: 'bold',
    },
    favoriteButton: {
        position: 'absolute',
        top: 8,
        right: 8,
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: 'rgba(255,255,255,0.9)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    bookInfo: {
        flex: 1,
    },
    bookTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#1a1a1a',
        marginBottom: 4,
        lineHeight: 20,
    },
    bookAuthor: {
        fontSize: 14,
        color: '#666',
        marginBottom: 8,
    },
    bookFooter: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    ratingContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    rating: {
        fontSize: 14,
        color: '#666',
        marginLeft: 4,
        fontWeight: '600',
    },
    price: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#2ecc71',
    },
    bookScroll: {
        padding: 1,
    },
});
