import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  card: {
    backgroundColor: '#fff',
    borderRadius: 20,
    marginHorizontal: 12,
    marginBottom: 18,
    padding: 16,
    elevation: 3,
    shadowColor: "#000",
    shadowOpacity: 0.07,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 3 },
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 2,
  },
  orderIdText: {
    color: "#F78104",
    fontSize: 15.5,
    fontWeight: "bold",
    letterSpacing: 0.2,
  },
  statusText: {
    fontWeight: "700",
    fontSize: 14,
    paddingVertical: 4,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: "#f6f9f6",
  },
  subheaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginVertical: 2,
    marginBottom: 7,
  },
  subheaderDate: {
    color: "#BABEC6",
    fontSize: 13,
    fontWeight: "500",
  },
  tableNameText: {
    color: "#6B47D6",
    fontSize: 13,
    fontWeight: "600",
  },
  booksList: {
    maxHeight: 145, // 2 book items  (adjust to bookImage + margins * 2)
    marginBottom: 10,
    marginTop: 2,
  },
  bookRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F7F5FA",
    borderRadius: 12,
    marginBottom: 10,
    paddingVertical: 6,
    paddingHorizontal: 8,
  },
  bookImage: {
    width: 46,
    height: 61,
    borderRadius: 9,
    backgroundColor: "#edeaff",
    marginRight: 12,
  },
  bookDetails: {
    flex: 1,
    minWidth: 72,
  },
  bookTitle: {
    fontSize: 15,
    fontWeight: "600",
    color: "#222d3a",
    marginBottom: 3,
  },
  detailsMeta: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
  },
  bookPrice: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#F78104",
  },
  bookQty: {
    fontSize: 13,
    color: "#6C7687",
    fontWeight: "500",
  },
  divider: {
    height: 1,
    backgroundColor: "#eeeeee",
    marginVertical: 7,
    marginHorizontal: -16,
  },
  rowBetween: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginVertical: 1,
  },
  infoLabel: {
    fontSize: 13,
    color: "#949494",
    fontWeight: "500",
  },
  infoValue: {
    fontSize: 15,
    color: "#222",
    fontWeight: "bold",
  },
  discountValue: {
    fontSize: 14,
    color: "#1EB676",
    fontWeight: "bold",
  },
  paymentContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  paymentMethod: {
    fontSize: 14,
    color: "#1976D2",
    fontWeight: "bold",
    marginRight: 7,
  },
  paidBadge: {
    backgroundColor: "#E0F7EC",
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 2,
    marginLeft: 3,
  },
  paidText: {
    fontSize: 13,
    color: "#20B86B",
    fontWeight: "700",
  },
});
